# -*- coding: utf-8 -*-
"""BDA2_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/yuvrajdevrukhkar/BDA-Lab/blob/main/BDA2_.ipynb

# Load the data from CSV file and split it into training and test datasets.
"""

import pandas as pd

df = pd.read_csv("diabetes.csv")

df.info()

df.head(10)

from sklearn.model_selection import train_test_split

x = df.drop("Outcome", axis = 1)
y = df['Outcome']

print(y)

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30, random_state=1)

"""# Summarize the properties in the training dataset so that we can calculate probabilities and make Predictions

"""

x_train

y_train

df.describe()

"""# Classify samples from the test dataset and a summarised traning dataset"""

from sklearn.naive_bayes import GaussianNB

# Creating a Gaussian classifier
model = GaussianNB()

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

from sklearn import metrics

print("accuracy: ", metrics.accuracy_score(y_test,y_pred))

